version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "azure/"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "aws/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
